version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  redis:
    image: redis:latest

  fastapi:
    image: mosaicshapes:latest
    ports:
      - 8080:80
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 80
    depends_on:
      - redis
      - rabbit

  worker:
    image: mosaicshapes:latest
    entrypoint: celery -A worker.tasks worker --loglevel=INFO
    volumes:
      - ./output:/output
      - ./tmp:/tmp
    depends_on:
      - redis
      - rabbit