version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  redis:
    image: redis:latest

  fastapi:
    image: mosaicshapes:latest
    ports:
      - 8080:80
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 80
    depends_on:
      - redis
      - rabbit

  worker:
    image: mosaicshapes:latest
    entrypoint: celery -A worker.tasks worker --loglevel=INFO
    volumes:
      - ./public:/public
      - ./tmp:/tmp
    environment:
      CELERY_BROKER_URL: pyamqp://guest@rabbit//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - rabbit

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: pyamqp://guest@rabbit//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - worker
      - redis